// src/core/constants.js

export const RENDERING = {
    VIEWPORT_WIDTH: 800,
    VIEWPORT_HEIGHT: 220,
    PIXELS_PER_SECOND: 120, // Deprecated in favor of dynamic calculation
    PIXELS_PER_BEAT: 100,     // New constant for beat-based positioning
    PLAYHEAD_X: 300,
    MARGIN_LEFT: 20,
    TREBLE_Y: 20,
    BASS_Y: 120,
    STAVE_LINE_WIDTH: 2,
    STAVE_CONNECTOR_OFFSET: 10,
    STAVE_CONNECTOR_BASS_EXTRA: 60,
    MIN_NOTES_CANVAS_WIDTH: 2400,
    NOTES_CANVAS_RIGHT_PADDING: 40,
    STAVE_WIDTH_REDUCTION: 20,
    VEXFLOW_INTRINSIC_OFFSET: 42,
    TREBLE_BASS_SPLIT_MIDI: 60,
    HALF_NOTE_DURATION_THRESHOLD: 1.5,
    VALIDATION_WINDOW_ALPHA: 0.3,
    VALIDATION_WINDOW_HEIGHT: 80,
    VALIDATION_WINDOW_LINE_WIDTH: 2,
    PLAYHEAD_LINE_WIDTH: 2,
    PLAYHEAD_COLOR: 'rgba(255,0,0,0.9)',
    BARLINE_OFFSET_X: 15,
};

export const BEATS = {
    WHOLE: 4.0,
    HALF: 2.0,
    QUARTER: 1.0,
    EIGHTH: 0.5,
    SIXTEENTH: 0.25,
    DOTTED_WHOLE: 6.0,
    DOTTED_HALF: 3.0,
    DOTTED_QUARTER: 1.5,
    DOTTED_EIGHTH: 0.75,
    EPSILON: 0.001
};

export const TIMING = {
    DEFAULT_TEMPO: 1.6,
    LEAD_IN_SECONDS: 3.0,
    STRICT_WINDOW_SECONDS: 0.10,
    SECONDS_IN_MINUTE: 60.0,
    STRICT_BEAT_TOLERANCE: 0.2,
    WIDE_BEAT_TOLERANCE: 0.5,
};

export const GENERATOR = {
    DEFAULT_MIN_MIDI: 60,
    DEFAULT_MAX_MIDI: 72,
    DEFAULT_COUNT: 20,
    DEFAULT_TEMPO_BPM: 80,
    DEFAULT_NOTE_DURATION_BEATS: 1.0,
    DEFAULT_NOTE_SPACING_BEATS: 0.0,
};

export const MIDI = {
    MIN_MIDI: 0,
    MAX_MIDI: 127,
    C4_MIDI: 60,
    OCTAVE_SIZE: 12,
    OCTAVE_OFFSET: 1,
};

export const COLORS = {
    BLACK: '#000',
    GREEN: 'green',
    VALIDATION_GREEN: 'rgba(0, 255, 0, 0.3)',
};
